"""Create users table

Revision ID: c58be3812127
Revises: 
Create Date: 2026-07-08 17:21:34.054995

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c58be3812127'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
